In [2]:
#only main codes

In [5]:
#numpy
import numpy as np
#to find numpy version
print(np.__version__)

1.23.5


In [6]:
#3d array
arr3=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(arr3)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [7]:
#creating array with 5D
arr=np.array([1,2,3],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3]]]]]
5


In [13]:
##reshaping array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
newarr = arr.reshape(3,3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
x =  np.arange(1,9+1).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#join two array
arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
arr = np.concatenate((arr1, arr2))
#print(arr1+arr2)
print(arr)

[1 2 3 1 2 3]


In [15]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [16]:
#make all zeros and ones
arr=np.zeros([3,3])
print(arr)
print()


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [18]:
##identity matrix
arr1=np.ones([3,3])
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#repeat number
a=np.repeat(5,10)
print(a)