In [2]:
#only main codes

In [5]:
#numpy
import numpy as np
#to find numpy version
print(np.__version__)

1.23.5


In [6]:
#3d array
arr3=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(arr3)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [7]:
#creating array with 5D
arr=np.array([1,2,3],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3]]]]]
5


In [13]:
##reshaping array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
newarr = arr.reshape(3,3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
x =  np.arange(1,9+1).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#join two array
arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
arr = np.concatenate((arr1, arr2))
#print(arr1+arr2)
print(arr)

[1 2 3 1 2 3]


In [15]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [16]:
#make all zeros and ones
arr=np.zeros([3,3])
print(arr)
print()


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [18]:
##identity matrix
arr1=np.ones([3,3])
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
#repeat number
a=np.repeat(5,10)
print(a)

[5 5 5 5 5 5 5 5 5 5]


In [51]:
#pandas
import pandas as pd
print(pd.__version__)

1.5.3


In [ ]:
#to read data
#data=pd.read_csv("copy paths")
#if excel file
#data=pd.read_excel('copy paths')

In [54]:
#making data like row and column
df=pd.DataFrame({'rollno':['1','2','3'],'name':['abhi','srk','shiv'],'mark':['80','90','85']})
df

rollno  name mark
0      1  abhi   80
1      2   srk   90
2      3  shiv   85

In [57]:
df['new_column']=np.nan
df

rollno  name mark  new_column
0      1  abhi   80         NaN
1      2   srk   90         NaN
2      3  shiv   85         NaN

In [60]:
df.rename(columns={'new_column':'hobby'},inplace=True)
df

rollno  name mark  hobby
0      1  abhi   80    NaN
1      2   srk   90    NaN
2      3  shiv   85    NaN

In [64]:
df['hobby']=['cricket','basketball','chess']
df
 

rollno  name mark       hobby
0      1  abhi   80     cricket
1      2   srk   90  basketball
2      3  shiv   85       chess

In [72]:
df.drop(columns=['mark'],inplace=True)
df

rollno  name       hobby
0      1  abhi     cricket
1      2   srk  basketball
2      3  shiv       chess

In [79]:
df1=df.replace(['abhi'],'abhinav')
df1

rollno     name       hobby
0      1  abhinav     cricket
1      2      srk  basketball
2      3     shiv       chess

In [89]:
#df1.rename({'shiv':'shivklumar'},inplace=True)
df1

rollno   name       hobby
0      1  abhin       pilot
1      2    srk  basketball
2      3   shiv       chess

In [91]:
df1.replace({'shiv':'shivklumar'},inplace=True)
df1

rollno        name       hobby
0      1       abhin       pilot
1      2         srk  basketball
2      3  shivklumar       chess

In [92]:
#making new data set
ndf=pd.DataFrame({'name':['chintu','pintu'],
                 'city':['nagpur','pune'],})
ndf

name    city
0  chintu  nagpur
1   pintu    pune

In [93]:
##adding column with data
ndf['hobby']=['chess','football']
ndf

name    city     hobby
0  chintu  nagpur     chess
1   pintu    pune  football

In [100]:
#add anathoer row
ndf1=ndf.append({'name':'ram','city':'nagpur','hobby':'javalin'},ignore_index=True)
ndf1

C:\Users\HP\AppData\Local\Temp\ipykernel_8352\1175935485.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ndf1=ndf.append({'name':'ram','city':'nagpur','hobby':'javalin'},ignore_index=True)


name    city     hobby
0  chintu  nagpur     chess
1   pintu    pune  football
2     ram  nagpur   javalin

In [103]:
ndf1['new_column']=np.nan
ndf1

name    city     hobby  new_column
0  chintu  nagpur     chess         NaN
1   pintu    pune  football         NaN
2     ram  nagpur   javalin         NaN

In [104]:
ndf1.drop(columns=['new_column'],inplace=True)
ndf1

name    city     hobby
0  chintu  nagpur     chess
1   pintu    pune  football
2     ram  nagpur   javalin

In [105]:
ndf1.replace({'chintu':'shardul'},inplace=True)
ndf1

name    city     hobby
0  shardul  nagpur     chess
1    pintu    pune  football
2      ram  nagpur   javalin

In [107]:
ndf1.rename(columns={'city':'hometown'},inplace=True)
ndf1

name hometown     hobby
0  shardul   nagpur     chess
1    pintu     pune  football
2      ram   nagpur   javalin

In [110]:
ndf2=ndf1.append({'name':'ram','city':'nagpur','hobby':'javalin'},ignore_index=True)
ndf2

C:\Users\HP\AppData\Local\Temp\ipykernel_8352\4220867777.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ndf2=ndf1.append({'name':'ram','city':'nagpur','hobby':'javalin'},ignore_index=True)


name    city     hobby
0  chintu  nagpur     chess
1   pintu    pune  football
2     ram  nagpur   javalin
3     ram  nagpur   javalin

In [114]:
ndf3=ndf2.append({'name':'ram','city':'nagpur','hobby':'javalin'},ignore_index=True)
ndf3

C:\Users\HP\AppData\Local\Temp\ipykernel_8352\3891469488.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ndf3=ndf2.append({'name':'ram','city':'nagpur','hobby':'javalin'},ignore_index=True)


name    city     hobby
0  chintu  nagpur     chess
1   pintu    pune  football
2     ram  nagpur   javalin
3     ram  nagpur   javalin
4     ram  nagpur   javalin